export const metadata = {
  title: 'Project 1 Website',
  description: 'Generated by Next.js',
}

import './globals.css'
import '/styles/GlobalsCustom.css'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </head>
      <body>{children}</body>
    </html>
  )
}
